const CODE = {
  // SUCCESS: 200,
  ACCOUNT_NOT_REGISTERD: 210,
  DUPLICATE_EMAIL: 211,
  DUPLICATE_NICKNAME: 212,
  INVALID_CREDENTIALS: 213,
  UNAUTHORIZED: 401,
  MISSING_ACCESS_TOKEN: 403,
};

module.exports = { CODE };
